const products = [
  {
    name: "Wedding Sherwani set",
    image: "/images/kurta7.jpg",
    description: "The Wild Masai Sherwani Set",
    brand: "PoShakh",
    category: "Men",
    price: 9700,
    countInStock: 10,
    rating: 4.7,
    numReviews: 12,
  },
  {
    name: "Sherwani for Grooms friend",
    image: "/images/kurta8.jpg",
    description: "hello ghghjg hhjhjk bhbh",
    brand: "PoShakh",
    category: "Men",
    price: 5999,
    countInStock: 7,
    rating: 4.0,
    numReviews: 8,
  },
  {
    name: "Wedding Collection",
    image: "/images/kurta2.jpg",
    description: "Celeste Mustard Kurta Set",
    brand: "PoShakh",
    category: "Women",
    price: 4500,
    countInStock: 5,
    rating: 3,
    numReviews: 12,
  },
  {
    name: "Halo Ivory Front Sherwani",
    image: "/images/kurta11.jpg",
    description: "Halo Ivory Front Open Sherwani",
    brand: "PoShakh",
    category: "Men",
    price: 35000,
    countInStock: 11,
    rating: 5,
    numReviews: 12,
  },
  {
    name: "Sherwani Set",
    image: "/images/kurta10.jpg",
    description: "please wear",
    brand: "PoShakh",
    category: "Men",
    price: 49999,
    countInStock: 7,
    rating: 3.5,
    numReviews: 10,
  },
  {
    name: "Vintage Sherwani",
    image: "/images/kurta5.jpg",
    description: "Saadi Vintage Ivory Sherwani Set",
    brand: "PoShakh",
    category: "Men",
    price: 29999,
    countInStock: 15,
    rating: 4,
    numReviews: 12,
  },
];

export default products;
